"""empty message

Revision ID: 3357fad12bb3
Revises: 5fa738f67ead
Create Date: 2020-01-28 22:32:09.305502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3357fad12bb3'
down_revision = '5fa738f67ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id', 'user', ['id'], unique=True)
    # ### end Alembic commands ###
