"""empty message

Revision ID: 61422f9aa54f
Revises: 3357fad12bb3
Create Date: 2020-01-28 22:33:12.159569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61422f9aa54f'
down_revision = '3357fad12bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
