"""empty message

Revision ID: ecf6617875ab
Revises: 61422f9aa54f
Create Date: 2020-01-28 23:47:37.926319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecf6617875ab'
down_revision = '61422f9aa54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=250), nullable=False),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('user_username', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tareas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('label', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_username', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_username'], ['user.username'], name='tareas_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('tarea')
    # ### end Alembic commands ###
